name: Workflow Principal

on: [workflow_dispatch]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: versão ubuntu
        run: |
          lsb_release -a
          node --version
          ls -lh
