name: Workflow Principal

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: versão ubuntu
        run: lsb_release -a
        
      - name: versão node
        run: node --version
