name: Workflow Principal

on: [workflow_dispatch]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: catch
        run: cat README.md
  
  dep:
    runs-on: ubuntu-latest
    needs: [ubuntu]
    steps:
      - name: condicao
        run: echo 'executou depois do ubuntu finalizou'
  
