name: Workflow Principal

on: 
  push:
    branches: [main]
  
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        
      - name: Run hello
        run: echo ${{ENV_TESTE}}
